version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre-build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run start